const cardData = [
  {
    id: 1,
    title: "Богиня изобилия и плут апостол",
    type: "Манхва",
    year: 2025,
    rating: 9.5,
    image: "/mokeImage/Carousel_1.webp",
    genres: ["Фэнтези", "Романтика"],
  },
  {
    id: 2,
    title: "Выбери меня!",
    type: "Манхва",
    year: 2022,
    rating: 9.6,
    image: "/mokeImage/Carousel_2.jpg",
    genres: ["Фэнтези", "Приключения"],
  },
  {
    id: 3,
    title: "Врата одиночества",
    type: "Манхва",
    year: 2023,
    rating: 8.9,
    image: "/mokeImage/Carousel_3.jpg",
    genres: ["Драма", "Психологическое"],
  },
  {
    id: 4,
    title: "Путь мечника",
    type: "Манга",
    year: 2024,
    rating: 9.2,
    image: "/mokeImage/Carousel_4.webp",
    genres: ["Боевик", "Фэнтези"],
  },
  {
    id: 5,
    title: "Тень империи",
    type: "Манхва",
    year: 2023,
    rating: 8.7,
    image: "/mokeImage/Carousel_5.webp",
    genres: ["Исторический", "Политика"],
  },
  {
    id: 6,
    title: "Звёздный охотник",
    type: "Манга",
    year: 2024,
    rating: 9.1,
    image: "/mokeImage/Carousel_6.webp",
    genres: ["Научная фантастика", "Приключения"],
  },
  {
    id: 7,
    title: "Мастер магии",
    type: "Манхва",
    year: 2025,
    rating: 9.3,
    image: "/mokeImage/Carousel_7.webp",
    genres: ["Фэнтези", "Магия"],
  },
  {
    id: 8,
    title: "Легенда о драконе",
    type: "Манга",
    year: 2023,
    rating: 8.8,
    image: "/mokeImage/Carousel_1.webp",
    genres: ["Фэнтези", "Приключения"],
  },
];

export default cardData;