/**
 * Метки (жанры/теги) из API Senkuro (fetchMangaFilters).
 * URL: https://api.senkuro.me/graphql, operationName: "fetchMangaFilters"
 * Используется для нормализации жанров: slug, EN и альтернативные названия → RU.
 */
export const SENKURO_LABELS_MAP: Record<string, string> = {
  // Корневые категории (depth 0)
  main_cast: "Основной каст",
  "main cast": "Основной каст",
  hentai_themes: "Хентайные Темы",
  "hentai-themes": "Хентайные Темы",
  traits: "Черты",
  setting: "Сеттинг",
  themes: "Темы",
  elements: "Элементы",
  demographics: "Демография",

  // Основной каст (main_cast)
  male_protagonist: "Главный герой мужчина",
  "male protagonist": "Главный герой мужчина",
  female_protagonist: "Главный герой женщина",
  "female protagonist": "Главный герой женщина",
  overpowered_protagonist: "Главный герой имба",
  "overpowered protagonist": "Главный герой имба",
  god_protagonist: "Главный герой бог",
  "god protagonist": "Главный герой бог",
  non_human_protagonist: "Главный герой не человек",
  "non human protagonist": "Главный герой не человек",
  smart_protagonist: "Умный Главный герой",
  "smart protagonist": "Умный Главный герой",
  stupid_protagonist: "Тупой Главный герой",
  "stupid protagonist": "Тупой Главный герой",
  young_protagonist: "Молодой Главный герой",
  "young protagonist": "Молодой Главный герой",
  elderly_protagonist: "Старый Главный герой",
  "elderly protagonist": "Старый Главный герой",
  antihero: "Антигерой",
  "anti-hero": "Антигерой",
  primarily_male_cast: "В основном мужчины",
  "primarily male cast": "В основном мужчины",
  primarily_female_cast: "В основном женщины",
  "primarily female cast": "В основном женщины",
  primarily_teen_cast: "В основном подростки",
  "primarily teen cast": "В основном подростки",
  primarily_adult_cast: "В основном взрослые",
  "primarily adult cast": "В основном взрослые",
  primarily_animal_cast: "В основном животные",
  "primarily animal cast": "В основном животные",
  mother: "Мать",
  son: "Сын",
  brother: "Брат",
  sister: "Сестра",
  grandfather: "Дедушка",
  old_man: "Старик",
  "old man": "Старик",
  stepfather: "Отчим",
  stepmother: "Мачеха",
  brother_and_sister: "Брат и сестра",
  "brother and sister": "Брат и сестра",

  // Хентайные темы (hentai_themes)
  big_breasts: "Большая грудь",
  "big breasts": "Большая грудь",
  huge_penis: "Огромный член",
  "huge penis": "Огромный член",
  big_penis: "Большой член",
  "big penis": "Большой член",
  vaginal: "Вагинальный",
  anal: "Анал",
  paizuri: "Пайзури",
  boobjob: "Пайзури",
  "стимуляция грудью": "Пайзури",
  group_sex: "Групповой Секс",
  "group sex": "Групповой Секс",
  mmf_threesome: "ММЖ Втроём",
  "mmf threesome": "ММЖ Втроём",
  masturbation: "Мастурбация",
  cum_in_pussy: "Вагинальный кремпай",
  "cum in pussy": "Вагинальный кремпай",
  nakadashi: "Вагинальный кремпай",
  creampie: "Вагинальный кремпай",
  deepthroat: "Глубокий Минет",
  rape: "Изнасилование",
  ahegao: "Ахегао",
  x_ray: "X-Ray",
  "x-ray": "X-Ray",
  futanari: "Футанари",
  dickgirl_on_female: "Футанари на женщине",
  "dickgirl on female": "Футанари на женщине",
  double_penetration: "Двойное проникновение",
  "double penetration": "Двойное проникновение",
  sex_toys: "Секс игрушки",
  "sex toys": "Секс игрушки",
  defloration: "Лишение девственности",
  pregnant: "Беременность",
  collar: "Ошейник",
  normal_sex: "Обычный секс",
  "normal sex": "Обычный секс",
  big_ass: "Большая попка",
  "big ass": "Большая попка",
  no_panties: "Без трусиков",
  "no panties": "Без трусиков",
  urination: "Мочеиспускание",
  gag: "Кляп",
  mature_female: "Зрелые женщины",
  "mature female": "Зрелые женщины",
  piercing: "Пирсинг",
  "stomach-deformation": "Деформация живота",
  stomach_deformation: "Деформация живота",
  virginity: "Девственность",
  shibari: "Шибари",
  humiliation: "Сексуальное унижение",
  big_nipples: "Большие соски",
  "big nipples": "Большие соски",
  oppai_loli: "Лоли с грудью",
  "oppai loli": "Лоли с грудью",
  bdsm: "БДСМ",
  bondage: "Бондаж",
  voyeur: "Наблюдение",
  вуайеризм: "Наблюдение",
  big_clit: "Большой клитор",
  "big clit": "Большой клитор",
  bodystocking: "Чулки на тело",
  human_on_furry: "Человек на фурри",
  "human on furry": "Человек на фурри",
  lots_sperm: "Много семени",
  "lots of sperm": "Много семени",
  young: "Юные",

  // Черты (traits)
  elf: "Эльф",
  angel: "Ангел",
  maid: "Горничная",
  мейдочка: "Горничная",
  villainess: "Злодейка",
  slave: "Раб",
  immortal: "Бессмертный",
  demon_girl: "Демонесса",
  "demon girl": "Демонесса",
  demon: "Демон",
  detective: "Детектив",
  dragon: "Драконы",
  evil_spirit: "Злой дух",
  "evil spirit": "Злой дух",
  ghost: "Призрак",
  дух: "Призрак",
  goblin: "Гоблин",
  orc: "Орк",
  knight: "Рыцарь",
  soldier: "Солдат",
  god: "Бог",
  goddess: "Богиня",
  beastmen: "Зверолюди",
  catgirl: "Девушка-кошка",
  "cat girl": "Девушка-кошка",
  mekomimi: "Девушка-кошка",
  кошкодевочка: "Девушка-кошка",
  snake_girl: "Девушка-змея",
  "snake girl": "Девушка-змея",
  centaur: "Кентавр",
  kemonomimi: "Ушастые",
  кемономими: "Ушастые",
  gyaru: "Гяру",
  гангуро: "Гяру",
  ganguro: "Гяру",
  kogal: "Гяру",
  когяру: "Гяру",
  delinquent: "Правонарушитель / Хулиган",
  хулиганы: "Правонарушитель / Хулиган",
  янки: "Правонарушитель / Хулиган",
  hikikomori: "Хикикомори",
  female_idol: "Идол",
  "female idol": "Идол",
  male_idol: "Идол",
  "male idol": "Идол",
  kuudere: "Кудере",
  loli: "Лоли",
  ninja: "Ниндзя",
  nurse: "Медсестра",
  office_lady: "Офисная леди",
  "office lady": "Офисная леди",
  office_workers: "Офисные работники",
  "office workers": "Офисные работники",
  ojou_sama: "Богатая леди",
  "ojou-sama": "Богатая леди",
  pirate: "Пират",
  robot: "Робот",
  samurai: "Самурай",
  teacher: "Учитель",
  tsundere: "Цундэрэ",
  yandere: "Яндере",
  vampire: "Вампир",
  witch: "Ведьма",
  zombie: "Зомби",
  monster: "Монстр",
  wizard: "Волшебник / Маг",
  monster_girl: "Монстродевушка",
  "monster girl": "Монстродевушка",
  undead: "Нежить",
  mercenary: "Наёмник",
  sentient_races: "Разумные расы",
  "sentient races": "Разумные расы",
  magical_creatures: "Волшебные существа",
  "magical creatures": "Волшебные существа",
  animal_companions: "Животные компаньоны",
  "animal companions": "Животные компаньоны",
  milf: "Милфы",
  criminal: "Криминал / Преступники",
  territory_management: "Управление территорией",
  "territory management": "Управление территорией",
  "kingdom management": "Управление территорией",
  aristocracy: "Аристократия",
  policewoman: "Женщина-полицейский",
  policeman: "Мужчина-полицейский",
  genki: "Генки",

  // Сеттинг (setting)
  cruel_world: "Жестокий мир",
  "cruel world": "Жестокий мир",
  ancient_world: "Древний мир",
  "ancient world": "Древний мир",
  dark_world: "Мрачный мир",
  "dark world": "Мрачный мир",
  apocalyptic: "Апокалиптический",
  "конец-света": "Апокалиптический",
  апокалипсис: "Апокалиптический",
  post_apocalyptic: "Постапокалиптический",
  "post-apocalyptic": "Постапокалиптический",
  dystopia: "Антиутопия",
  middle_ages: "Средневековье",
  "middle ages": "Средневековье",
  fantasy_world: "Фэнтезийный мир",
  "fantasy world": "Фэнтезийный мир",
  steampunk: "Стимпанк",
  cyberpunk: "Киберпанк",
  underworld: "Подземный мир",
  future: "Будущее",
  alternative_present: "Альтернативное настоящее",
  "alternative present": "Альтернативное настоящее",
  alternate_universe: "Альтернативная вселенная",
  "alternate universe": "Альтернативная вселенная",
  historical: "Исторический",
  world_war_2: "Вторая мировая война",
  "world war ii": "Вторая мировая война",
  school: "Школа",
  middle_school: "Средняя школа",
  "middle school": "Средняя школа",
  secondary_school: "Старшая школа",
  "secondary school": "Старшая школа",
  magic_academy: "Магическая академия",
  "magic academy": "Магическая академия",
  office: "Офис",
  urban: "В городе",
  urban_fantasy: "Городское фэнтези",
  "urban fantasy": "Городское фэнтези",
  educational_institution: "Учебное заведение",
  "educational institution": "Учебное заведение",
  public_place: "Общественное место",
  "public place": "Общественное место",
  coastal: "Прибрежный",
  space: "Космос",
  korea: "Корея",
  japan: "Япония",

  // Темы (themes)
  hiding_identity: "Сокрытие личности",
  "hiding identity": "Сокрытие личности",
  power_ranks: "Ранги силы",
  "power ranks": "Ранги силы",
  power_struggle: "Борьба за власть",
  "power struggle": "Борьба за власть",
  another_world_memory: "Воспоминания из другого мира",
  "another world memory": "Воспоминания из другого мира",
  cultivation: "Культивация",
  культяпки: "Культивация",
  reincarnation: "Реинкарнация",
  skills: "Навыки / Способности",
  magic: "Магия",
  saving_the_world: "Спасение мира",
  "saving the world": "Спасение мира",
  violence: "Насилие / Жестокость",
  gore: "Насилие / Жестокость",
  maou: "Владыка демонов",
  system: "Система",
  литрпг: "Система",
  game_elements: "Игровые элементы",
  "game elements": "Игровые элементы",
  "элементы рпг": "Игровые элементы",
  dungeon: "Подземелье",
  guilds: "Гильдии",
  necromancy: "Некромантия",
  character_growth: "Рост персонажа",
  "character growth": "Рост персонажа",
  vr: "Виртуальная реальность",
  ar: "Дополненная реальность",
  survival: "Выживание",
  crime: "Преступления",
  mafia: "Мафия",
  yakuza: "Якудза",
  legendary_weapon: "Легендарное оружие",
  "legendary weapon": "Легендарное оружие",
  world_conquest: "Завоевание мира",
  "world conquest": "Завоевание мира",
  alchemy: "Алхимия",
  romance: "Романтика",
  love_polygon: "Любовный многоугольник",
  "love polygon": "Любовный многоугольник",
  "любовный треугольник": "Любовный многоугольник",
  female_harem: "Женский гарем",
  "female harem": "Женский гарем",
  male_harem: "Мужской гарем",
  "male harem": "Мужской гарем",
  "обратный гарем": "Мужской гарем",
  teens_love: "Любовь подростков",
  "teens' love": "Любовь подростков",
  incest: "Инцест",
  marriage: "Свадьба",
  comedy: "Комедия",
  elements_of_humor: "Элементы юмора",
  "elements of humor": "Элементы юмора",
  parody: "Пародия",
  fantasy: "Фэнтези",
  isekai: "Исекай",
  "путешествие в другой мир": "Исекай",
  superpower: "Супер сила",
  superheroes: "Супергерои",
  heroic_fantasy: "Героическое фэнтези",
  "heroic fantasy": "Героическое фэнтези",
  action: "Экшен",
  swordplay: "Бои на мечах",
  gunfights: "Перестрелки",
  martial_arts: "Боевые искусства",
  "martial arts": "Боевые искусства",
  army: "Армия",
  artifacts: "Артефакты",
  blackmail: "Шантаж",
  body_swap: "Обмен телами",
  friendship: "Дружба",
  gamers: "Геймеры",
  madness: "Безумие",
  rebellion: "Восстание",
  medicine: "Медицина",
  royal_affairs: "Королевские дела",
  "royal affairs": "Королевские дела",
  philosophy: "Философия",
  police: "Полиция",
  politics: "Политика",
  quests: "Квесты",
  firearms: "Огнестрельное оружие",
  steel_arms: "Холодное оружие",
  "steel arms": "Холодное оружие",
  slavery: "Рабство",
  gambling: "Азартные игры",
  гэмблинг: "Азартные игры",
  moving_between_worlds: "Перемещение между мирами",
  "moving between worlds": "Перемещение между мирами",
  mythology: "Мифология",
  empire: "Империи",
  cat_wife: "Кошка-жена",
  "cat wife": "Кошка-жена",
  mahou_shoujo: "Девочки-волшебницы",
  "mahou shoujo": "Девочки-волшебницы",
  "махо-сёдзё": "Девочки-волшебницы",
  music: "Музыка",
  school_life: "Школьная жизнь",
  "school life": "Школьная жизнь",
  murim: "Мурим",
  drugs: "Наркотики",
  torture: "Пытки",
  gender_intrigue: "Гендерная интрига",
  "gender intrigue": "Гендерная интрига",
  "gender bending": "Гендерная интрига",
  smoking: "Курение",
  educational: "Образовательное",
  religion: "Религия",
  afterlife: "Загробная жизнь",
  otaku_culture: "Культура Отаку",
  "otaku culture": "Культура Отаку",
  cult: "Культ",
  drama: "Драма",
  tragedy: "Трагедия",
  conspiracy: "Заговор",
  revenge: "Месть",
  arranged_marriage: "Брак по договорённости",
  "arranged marriage": "Брак по договорённости",
  art: "Искусство",
  drawing: "Рисование",
  "изобразительное искусство": "Рисование",
  "visual arts": "Рисование",
  avant_garde: "Авангард",
  "avant garde": "Авангард",
  gourmet: "Гурман",
  cooking: "Кулинария",
  кулинария: "Гурман",
  travel: "Путешествие",
  showbiz: "Шоу-бизнес",
  slice_of_life: "Повседневность",
  "slice of life": "Повседневность",
  working_life: "Работа",
  "working life": "Работа",
  работа: "Работа",
  iyashikei: "Иясикэй",
  cute_girls_doing_cute_things: "Милые девушки, делающие милые вещи",
  "cute girls doing cute things": "Милые девушки, делающие милые вещи",
  cgdct: "Милые девушки, делающие милые вещи",
  sport: "Спорт",
  football: "Футбол",
  cheerleading: "Черлидинг",
  motorsport: "Автоспорт",
  curse: "Проклятие",
  ecchi: "Этти",
  sci_fi: "Фантастика",
  "sci-fi": "Фантастика",
  time_manipulation: "Манипуляция временем / Путешествия",
  "time manipulation": "Манипуляция временем / Путешествия",
  "time travel": "Манипуляция временем / Путешествия",
  "путешествие во времени": "Манипуляция временем / Путешествия",
  supernatural: "Сверхъестественное",
  adventure: "Приключения",
  mystery: "Мистика",
  mecha: "Меха",
  military: "Военное",
  war: "Война",
  psychological: "Психологическое",
  amnesia: "Амнезия / Потеря памяти",
  horror: "Ужасы",
  psychological_horror: "Психологический ужас",
  "psychological horror": "Психологический ужас",
  thriller: "Триллер",
  games: "Игры",
  high_stakes_game: "Игра с высокими ставками",
  "high stakes game": "Игра с высокими ставками",
  "смертельная игра": "Игра с высокими ставками",
  traditional_games: "Традиционные игры",
  "traditional games": "Традиционные игры",
  video_games: "Видеоигры",
  "video games": "Видеоигры",
  psychosexual: "Психосексуальный",
  erotica: "Эротика",
  hentai: "Хентай",
  yuri: "Юри",
  yaoi: "Яой",
  team_sport: "Командный спорт",
  "team sport": "Командный спорт",
  gag_humor: "Гэг-юмор",
  "gag humor": "Гэг-юмор",
  "визуальный юмор": "Гэг-юмор",
  "visual humor": "Гэг-юмор",

  // Элементы (elements)
  stockings: "Чулки",
  glasses: "Очки",
  school_uniform: "Школьная форма",
  "school uniform": "Школьная форма",
  schoolboy_uniform: "Школьная форма мальчиков",
  "school uniform for girls": "Школьная форма мальчиков",
  swimsuit: "Купальник",
  horns: "Рога",
  wings: "Крылья",
  mind_control: "Промывание мозгов",
  "mind control": "Промывание мозгов",
  unusual_pupils: "Необычные зрачки",
  "unusual pupils": "Необычные зрачки",
  long_hair: "Длинные волосы",
  "long hair": "Длинные волосы",
  business_suit: "Деловой костюм",
  "business suit": "Деловой костюм",
  dark_skin: "Тёмнокожие",
  "dark skin": "Тёмнокожие",
  masked_face: "Лицо в маске",
  "masked face": "Лицо в маске",
  scar: "Шрам",
  chinese_dress: "Китайская одежда",
  "chinese dress": "Китайская одежда",
  athletic_body: "Спортивное тело",
  "athletic body": "Спортивное тело",
  tall_girl: "Высокая девушка",
  "tall girl": "Высокая девушка",
  tall_man: "Высокий мужчина",
  "tall man": "Высокий мужчина",
  blood: "Кровь",
  mental_illness: "Психические отклонения",
  "mental illness": "Психические отклонения",
  crossdressing: "Кроссдрессинг",
  gender_change: "Смена пола",
  "gender change": "Смена пола",
  "гендерный морф": "Смена пола",
  "gender morph": "Смена пола",
  tone_changes: "Изменения тона",
  "tone changes": "Изменения тона",
  with_plot: "С Сюжетом",
  "with a plot": "С Сюжетом",
  sex: "Секс",
  uncensored: "Без цензуры",

  // Демография (demographics)
  shounen: "Сёнен",
  shounen_ai: "Сёнен-ай",
  "shounen ai": "Сёнен-ай",
  "любовь мальчиков": "Сёнен-ай",
  "boys' love": "Сёнен-ай",
  seinen: "Сэйнэн",
  shoujo: "Сёдзе",
  shoujo_ai: "Сёдзе-ай",
  "shoujo ai": "Сёдзе-ай",
  "любовь девочек": "Сёдзе-ай",
  "girls love": "Сёдзе-ай",
  josei: "Дзёсей",
  xianxia: "Сянься",
  kids: "Детское",
};
