import type { Metadata } from "next";
import { Exo_2, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const exo_2 = Exo_2({
  variable: "--font-exo_2",
  weight: ["200", "400", "700"],
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${exo_2.variable} ${geistMono.variable} antialiased w-full justify-center items-center`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
