export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/titles/",
          "/collections/",
          "/top/",
          "/updates/",
          "/copyright/",
          "/terms-of-use/",
          "/about/",
          "/contact/",
          "/rss/",
        ],
        disallow: [
          "/admin/",
          "/profile/",
          "/tomilo-shop/",
          "/api/",
          "/settings/",
          "/notifications/",
          "/history/",
          "/bookmarks/",
          "/auth/",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: ["/rss/", "/titles/", "/collections/"],
        disallow: ["/admin/", "/profile/", "/api/", "/browse/"],
      },
      {
        userAgent: "Yandex",
        allow: [
          "/",
          "/titles/",
          "/collections/",
          "/top/",
          "/updates/",
          "/copyright/",
          "/terms-of-use/",
          "/about/",
          "/contact/",
          "/rss/",
        ],
        disallow: [
          "/admin/",
          "/browse/",
          "/profile/",
          "/tomilo-shop/",
          "/api/",
          "/settings/",
          "/notifications/",
          "/history/",
          "/bookmarks/",
          "/auth/",
        ],
      },
      {
        userAgent: "Bingbot",
        allow: ["/rss/", "/titles/", "/collections/"],
        disallow: ["/admin/", "/profile/", "/api/", "/browse/"],
      },
    ],
    sitemap: `${process.env.NEXT_PUBLIC_URL || "https://tomilo-lib.ru"}/sitemap.xml`,
    host: process.env.NEXT_PUBLIC_URL || "https://tomilo-lib.ru",
  };
}
